---
abstract: 'show a single character like a segmented display'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::More: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tickit-Widget-SegmentDisplay
provides:
  Tickit::Widget::SegmentDisplay:
    file: lib/Tickit/Widget/SegmentDisplay.pm
    version: 0.02
requires:
  Tickit::Test: 0.12
  Tickit::Widget: 0.36
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
